name: React Vite test 

on: [push, pull_request]

jobs:
    react-test:
        runs-on: ubuntu-latest

        steps:
          -  name: Checkout code
             uses: actions/checkout

             - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
